version: "3.3"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 4000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 5000:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9000:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
